[versions]
flyway = "10.15.2"
spotless = "6.25.0"
mysql = "8.4.0"

[plugins]
flyway = { id = "org.flywaydb.flyway", version.ref = "flyway" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }

[libraries]
mysql = { module = "com.mysql:mysql-connector-j", version.ref = "mysql" }
flyway-mysql = { module = "org.flywaydb:flyway-mysql", version.ref = "flyway" }
